apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ../hasura-pgsql
- example-test-tls-secret.yaml

patchesStrategicMerge:
- deployment.yaml

# optional:
#- ../with-istio # remember to customize you host field

# common labels deliberately skipped

namespace: app
