/**
 * MFA-related types for authentication flow.
 *
 * Response types use snake_case to match Auth0 API conventions (consistent with SPA SDK).
 * SDK-facing types use camelCase.
 */

import type { MfaRequirements } from "../errors/index.js";

/**
 * Auth0 MFA API response types (snake_case).
 * These represent raw API responses before transformation to SDK types.
 */

/**
 * Authenticator response from Auth0 API (snake_case).
 * Maps to {@link Authenticator} in SDK-facing interface.
 */
export interface AuthenticatorApiResponse {
  /** Authenticator ID */
  id: string;
  /** Authenticator type (primary field) */
  authenticator_type: string;
  /** Direct type value (optional, feature-flagged field) */
  type?: string;
  /** Whether authenticator is active */
  active: boolean;
  /** Authenticator name (user-defined or default) */
  name?: string;
  /** Phone number for OOB (masked) */
  phone_number?: string;
  /** OOB channel (sms, voice) */
  oob_channel?: string;
  /** ISO 8601 timestamp of creation */
  created_at?: string;
  /** ISO 8601 timestamp of last authentication */
  last_auth?: string;
}

/**
 * Challenge response from Auth0 API (snake_case).
 * Maps to {@link ChallengeResponse} in SDK-facing interface.
 */
export interface ChallengeApiResponse {
  /** Challenge type (otp, oob) */
  challenge_type: string;
  /** OOB code (for oob challenges) */
  oob_code?: string;
  /** Binding method (for oob challenges) */
  binding_method?: string;
}

/**
 * Enrollment response from Auth0 API (snake_case).
 * Maps to {@link EnrollmentResponse} in SDK-facing interface.
 */
export interface EnrollmentApiResponse {
  /** Authenticator type discriminator */
  authenticator_type: "otp" | "oob" | "email";
  /** Authenticator ID */
  id: string;
  /** Recovery codes (first enrollment only) */
  recovery_codes?: string[];
  /** TOTP secret (otp only - required for otp) */
  secret?: string;
  /** Barcode URI (otp only - required for otp) */
  barcode_uri?: string;
  /** OOB channel (oob only - required for oob) */
  oob_channel?: "sms" | "voice" | "auth0";
  /** Authenticator name (oob/email only) */
  name?: string;
}

/**
 * Request body for verify endpoint (pre-validation).
 * Contains at least one verification credential.
 */
export interface VerifyCredentialBody {
  /** OTP code (6 digits) */
  otp?: string;
  /** OOB code from challenge */
  oobCode?: string;
  /** Binding code for OOB */
  bindingCode?: string;
  /** Recovery code */
  recoveryCode?: string;
}

/**
 * Grant type for MFA token exchange.
 * Used in token endpoint requests to exchange an mfa_token for access/refresh tokens.
 *
 * @see https://auth0.com/docs/api/authentication#verify-with-one-time-password-otp-
 */
export const GRANT_TYPE_MFA_OTP = "http://auth0.com/oauth/grant-type/mfa-otp";

/**
 * Grant type for MFA OOB (SMS/Email/Push) verification.
 *
 * @see https://auth0.com/docs/api/authentication#verify-with-oob
 */
export const GRANT_TYPE_MFA_OOB = "http://auth0.com/oauth/grant-type/mfa-oob";

/**
 * Grant type for MFA recovery code verification.
 *
 * @see https://auth0.com/docs/api/authentication#verify-with-recovery-code
 */
export const GRANT_TYPE_MFA_RECOVERY_CODE =
  "http://auth0.com/oauth/grant-type/mfa-recovery-code";

/**
 * MFA verify response from Auth0.
 * Uses snake_case to match Auth0 API and SPA SDK conventions.
 *
 * @see https://auth0.com/docs/api/authentication#verify-with-one-time-password-otp-
 */
export interface MfaVerifyResponse {
  /** Access token */
  access_token: string;
  /** Refresh token (if present) */
  refresh_token?: string;
  /** ID token (if present) */
  id_token?: string;
  /** Token type (usually "Bearer") */
  token_type: string;
  /** Token scope */
  scope?: string;
  /** API audience */
  audience?: string;
  /** Expires in seconds */
  expires_in: number;
  /** Recovery code (if regenerated by tenant config) */
  recovery_code?: string;
}

/**
 * Enroll OTP authenticator (TOTP app like Authy/Google Authenticator).
 */
export interface EnrollOtpOptions {
  /** Encrypted MFA token */
  mfaToken: string;
  /** Authenticator types to enroll */
  authenticatorTypes: ["otp"];
}

/**
 * Enroll OOB authenticator (SMS/Voice/Push).
 */
export interface EnrollOobOptions {
  /** Encrypted MFA token */
  mfaToken: string;
  /** Authenticator types to enroll */
  authenticatorTypes: ["oob"];
  /** OOB channels (sms, voice, auth0) */
  oobChannels: ("sms" | "voice" | "auth0")[];
  /** Phone number in E.164 format (required for sms/voice) */
  phoneNumber?: string;
}

/**
 * Enroll Email authenticator.
 */
export interface EnrollEmailOptions {
  /** Encrypted MFA token */
  mfaToken: string;
  /** Authenticator types to enroll */
  authenticatorTypes: ["email"];
  /** Email address (optional - uses user's email if not provided) */
  email?: string;
}

/**
 * MFA enrollment options (discriminated union).
 */
export type EnrollOptions =
  | EnrollOtpOptions
  | EnrollOobOptions
  | EnrollEmailOptions;

/**
 * OTP enrollment response.
 */
export interface OtpEnrollmentResponse {
  /** Authenticator type discriminator */
  authenticatorType: "otp";
  /** TOTP secret (for QR code generation) */
  secret: string;
  /** Barcode URI (otpauth:// format) */
  barcodeUri: string;
  /** Recovery codes (first enrollment only) */
  recoveryCodes?: string[];
  /** Authenticator ID */
  id: string;
}

/**
 * OOB enrollment response (SMS/Voice/Push).
 */
export interface OobEnrollmentResponse {
  /** Authenticator type discriminator */
  authenticatorType: "oob";
  /** OOB channel */
  oobChannel: "sms" | "voice" | "auth0";
  /** Recovery codes (first enrollment only) */
  recoveryCodes?: string[];
  /** Authenticator ID */
  id: string;
  /** Authenticator name */
  name?: string;
}

/**
 * Email enrollment response.
 */
export interface EmailEnrollmentResponse {
  /** Authenticator type discriminator */
  authenticatorType: "email";
  /** Recovery codes (first enrollment only) */
  recoveryCodes?: string[];
  /** Authenticator ID */
  id: string;
  /** Authenticator name */
  name?: string;
}

/**
 * MFA enrollment response (discriminated union).
 */
export type EnrollmentResponse =
  | OtpEnrollmentResponse
  | OobEnrollmentResponse
  | EmailEnrollmentResponse;

/**
 * MFA client interface available in both server and client contexts.
 */
export interface MfaClient {
  /**
   * List enrolled authenticators for the user.
   * Filters by allowed challenge types from mfa_requirements.
   *
   * @param options - Options containing encrypted mfaToken
   * @returns Array of authenticators
   */
  getAuthenticators(options: { mfaToken: string }): Promise<Authenticator[]>;

  /**
   * Initiate an MFA challenge.
   *
   * @param options - Challenge options
   * @returns Challenge response (oobCode, bindingMethod)
   */
  challenge(options: {
    mfaToken: string;
    challengeType: string;
    authenticatorId?: string;
  }): Promise<ChallengeResponse>;

  /**
   * Delete an enrolled MFA authenticator.
   *
   * @param options - Delete options containing encrypted mfaToken and authenticatorId
   * @returns Promise that resolves when deletion succeeds
   */
  deleteAuthenticator(options: {
    mfaToken: string;
    authenticatorId: string;
  }): Promise<void>;

  /**
   * Verify MFA code and complete authentication.
   * Caches resulting access token in session.
   *
   * @param options - Verification options (otp | oobCode+bindingCode | recoveryCode)
   * @returns Token response with access token, refresh token, etc.
   */
  verify(options: VerifyMfaOptions): Promise<MfaVerifyResponse>;

  /**
   * Enroll a new MFA authenticator during initial MFA setup.
   *
   * @param options - Enrollment options (otp | oob | email)
   * @returns Enrollment response with authenticator details and optional recovery codes
   */
  enroll(options: EnrollOptions): Promise<EnrollmentResponse>;
}

/**
 * MFA authenticator (enrolled factor).
 * Uses camelCase for SDK-facing interface.
 */
export interface Authenticator {
  /** Authenticator ID */
  id: string;
  /** Authenticator type (primary field mapped from authenticator_type) */
  authenticatorType: string;
  /** Direct type value (optional, feature-flagged field from Auth0 API) */
  type?: string;
  /** Whether authenticator is active */
  active: boolean;
  /** Authenticator name (user-defined or default) */
  name?: string;
  /** Phone number for OOB (masked) */
  phoneNumber?: string;
  /** OOB channel (sms, voice) */
  oobChannel?: string;
  /** ISO 8601 timestamp of creation */
  createdAt?: string;
  /** ISO 8601 timestamp of last authentication */
  lastAuthenticatedAt?: string;
}

/**
 * MFA challenge response.
 * Uses camelCase for SDK-facing interface.
 */
export interface ChallengeResponse {
  /** Challenge type (otp, oob) */
  challengeType: string;
  /** OOB code (for oob challenges) */
  oobCode?: string;
  /** Binding method (for oob challenges) */
  bindingMethod?: string;
}

/**
 * Base options for MFA verify.
 */
export interface VerifyMfaOptionsBase {
  /** Encrypted MFA token */
  mfaToken: string;
}

/**
 * Verify with OTP code.
 */
export interface VerifyMfaWithOtpOptions extends VerifyMfaOptionsBase {
  otp: string;
}

/**
 * Verify with OOB code and binding code.
 */
export interface VerifyMfaWithOobOptions extends VerifyMfaOptionsBase {
  oobCode: string;
  bindingCode: string;
}

/**
 * Verify with recovery code.
 */
export interface VerifyMfaWithRecoveryCodeOptions extends VerifyMfaOptionsBase {
  recoveryCode: string;
}

/**
 * MFA verification options (union type).
 */
export type VerifyMfaOptions =
  | VerifyMfaWithOtpOptions
  | VerifyMfaWithOobOptions
  | VerifyMfaWithRecoveryCodeOptions;

/**
 * MFA context embedded in encrypted token.
 * Self-contained with all information needed for challenge completion.
 */
export interface MfaContext {
  /** Raw mfa_token from Auth0 */
  mfaToken: string;
  /** API identifier that required MFA */
  audience: string;
  /** Scopes requested */
  scope: string;
  /** MFA requirements from Auth0 */
  mfaRequirements: MfaRequirements | undefined;
  /** Timestamp for TTL validation (milliseconds since epoch) */
  createdAt: number;
}
