/**
 * MFA-related types for authentication flow.
 * 
 * Response types use snake_case to match Auth0 API conventions (consistent with SPA SDK).
 * SDK-facing types use camelCase.
 */

import type { MfaRequirements } from "../errors/index.js";

/**
 * MFA verify response from Auth0.
 * Uses snake_case to match Auth0 API and SPA SDK conventions.
 * 
 * @see https://auth0.com/docs/api/authentication#verify-with-one-time-password-otp-
 */
export interface MfaVerifyResponse {
  /** Access token */
  access_token: string;
  /** Refresh token (if present) */
  refresh_token?: string;
  /** ID token (if present) */
  id_token?: string;
  /** Token type (usually "Bearer") */
  token_type: string;
  /** Token scope */
  scope?: string;
  /** API audience */
  audience?: string;
  /** Expires in seconds */
  expires_in: number;
  /** Recovery code (if regenerated by tenant config) */
  recovery_code?: string;
}

/**
 * MFA client interface available in both server and client contexts.
 */
export interface MfaClient {
  /**
   * List enrolled authenticators for the user.
   * Filters by allowed challenge types from mfa_requirements.
   * 
   * @param options - Options containing encrypted mfaToken
   * @returns Array of authenticators
   */
  getAuthenticators(options: { mfaToken: string }): Promise<Authenticator[]>;

  /**
   * Initiate an MFA challenge.
   * 
   * @param options - Challenge options
   * @returns Challenge response (oobCode, bindingMethod)
   */
  challenge(options: {
    mfaToken: string;
    challengeType: string;
    authenticatorId?: string;
  }): Promise<ChallengeResponse>;

  /**
   * Verify MFA code and complete authentication.
   * Caches resulting access token in session.
   * 
   * @param options - Verification options (otp | oobCode+bindingCode | recoveryCode)
   * @returns Token response with access token, refresh token, etc.
   */
  verify(options: VerifyMfaOptions): Promise<MfaVerifyResponse>;
}

/**
 * MFA authenticator (enrolled factor).
 * Uses camelCase for SDK-facing interface.
 */
export interface Authenticator {
  /** Authenticator ID */
  id: string;
  /** Authenticator type (otp, oob, recovery-code, etc.) */
  type: string;
  /** Whether authenticator is active */
  active: boolean;
  /** Authenticator name (user-defined or default) */
  name?: string;
  /** Phone number for OOB (masked) */
  phoneNumber?: string;
  /** OOB channel (sms, voice) */
  oobChannel?: string;
  /** ISO 8601 timestamp of creation */
  createdAt?: string;
  /** ISO 8601 timestamp of last authentication */
  lastAuthenticatedAt?: string;
}

/**
 * MFA challenge response.
 * Uses camelCase for SDK-facing interface.
 */
export interface ChallengeResponse {
  /** Challenge type (otp, oob) */
  challengeType: string;
  /** OOB code (for oob challenges) */
  oobCode?: string;
  /** Binding method (for oob challenges) */
  bindingMethod?: string;
}

/**
 * Base options for MFA verify.
 */
export interface VerifyMfaOptionsBase {
  /** Encrypted MFA token */
  mfaToken: string;
}

/**
 * Verify with OTP code.
 */
export interface VerifyMfaWithOtpOptions extends VerifyMfaOptionsBase {
  otp: string;
}

/**
 * Verify with OOB code and binding code.
 */
export interface VerifyMfaWithOobOptions extends VerifyMfaOptionsBase {
  oobCode: string;
  bindingCode: string;
}

/**
 * Verify with recovery code.
 */
export interface VerifyMfaWithRecoveryCodeOptions extends VerifyMfaOptionsBase {
  recoveryCode: string;
}

/**
 * MFA verification options (union type).
 */
export type VerifyMfaOptions =
  | VerifyMfaWithOtpOptions
  | VerifyMfaWithOobOptions
  | VerifyMfaWithRecoveryCodeOptions;

/**
 * MFA context embedded in encrypted token.
 * Self-contained with all information needed for challenge completion.
 */
export interface MfaContext {
  /** Raw mfa_token from Auth0 */
  mfaToken: string;
  /** API identifier that required MFA */
  audience: string;
  /** Scopes requested */
  scope: string;
  /** MFA requirements from Auth0 */
  mfaRequirements: MfaRequirements | undefined;
  /** Timestamp for TTL validation (milliseconds since epoch) */
  createdAt: number;
}
