import './globals.css';
import { getSession } from '@auth0/nextjs-auth0';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Nav from '@/app/nav';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // this will emit a warning because Server Components cannot write to cookies
  // see https://github.com/auth0/nextjs-auth0#using-this-sdk-with-react-server-components
  const session = await getSession();

  return (
    <html lang="en">
      <UserProvider user={session?.user}>
        <body>
          <header>
            <Nav />
          </header>
          <div className="container">{children}</div>
        </body>
      </UserProvider>
    </html>
  );
}
