name: RL-Secure
run-name: rl-scanner

on:
  merge_group:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  rl-scanner:
    if: github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'release/'))
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install npm dependencies
        run: npm ci

      - name: Build Dist Folder
        run: npm run build

      - name: Create tgz build artifact
        run: |
          tar -czvf nextjs-auth0.tgz *
      - name: Get Artifact Version
        id: get_version
        run: echo "version=$(cat .version)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install boto3 requests
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.PRODSEC_TOOLS_ARN }}
          aws-region: us-east-1
          mask-aws-account-id: true

      - name: Run Reversing Labs Wrapper Scanner
        env:
          RLSECURE_LICENSE: ${{ secrets.RLSECURE_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
          SIGNAL_HANDLER_TOKEN: ${{ secrets.SIGNAL_HANDLER_TOKEN }}
          WRAPPER_INDEX_URL: "https://${{ secrets.PRODSEC_TOOLS_USER }}:${{ secrets.PRODSEC_TOOLS_TOKEN }}@a0us.jfrog.io/artifactory/api/pypi/python-local/simple"
          PYTHONUNBUFFERED: 1
        run: |
          pip install rl-wrapper --index-url $WRAPPER_INDEX_URL && \
          rl-wrapper \
            --artifact "$(pwd)/node-auth0.tgz" \
            --name "${{ github.event.repository.name }}" \
            --version "${{ steps.get_version.outputs.version }}" \
            --repository "${{ github.repository }}" \
            --commit "${{ github.sha }}" \
            --build-env "github_action"