apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- namespace.yaml
- service.yaml

commonLabels:
  app: with-apollo-hasura-ssr
  component: app
  tier: frontend

namespace: app
